homeassistant:
  # Name of the location where Home Assistant is running
  name: Genio
  # Location required to calculate the time the sun rises and sets
  latitude: -19.939623
  longitude: -43.998239
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 830
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Sao_Paulo
  # Customization file
  customize: !include customize.yaml
# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://127.0.0.1:3218

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

# Discover some devices automatically
# discovery:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Cloud
# cloud:

#
media_player:
  - platform: vlc
    name: speaker
    arguments: '--alsa-audio-device=hw:0,0'

# Text to speech
speech:
  speech_rate: 160
  voice: 'brazil'


mqtt: 
  broker: localhost   #if broker installed on the same computer than Home-Assistant 
  client_id: home-assistant
  discovery: true
  discovery_prefix: hass
  keepalive: 60
  port: 1883          #by default 
  protocol: 3.1       #by default
  #username: USERNAME #optional
  #password: PASSWORD #optional


switch:
  - platform: mqtt
    name: "luz da sala"
    state_topic: "hass/switch/sala/luz1/status"
    command_topic: "hass/switch/sala/luz1/set"
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: true
    qos: 0
    retain: true
    value_template: '{{ value.x }}'
  - platform: mqtt
    name: "luz do quarto"
    state_topic: "hass/switch/quarto/luz1/status"
    command_topic: "hass/switch/quarto/luz1/set"
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: true
    qos: 0
    retain: true
    value_template: '{{ value.x }}'
  - platform: mqtt
    name: "luz da cozinha"
    state_topic: "hass/switch/cozinha/luz1/status"
    command_topic: "hass/switch/cozinha/luz1/set"
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: true
    qos: 0
    retain: true
    value_template: '{{ value.x }}'
  - platform: mqtt
    name: "porta da sala"
    state_topic: "hass/switch/sala/porta1/status"
    command_topic: "hass/switch/sala/porta1/set"
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: true
    qos: 0
    retain: true
    value_template: '{{ value.x }}'


input_boolean:
  successful_command:
    name: 'Command Success'
    initial: off
    icon: mdi:playlist-check

# Wakeword detection
hotword_snowboy:
  model: /opt/cefetmg/data/snowboy/genio.pmdl
  name: hotword_genio


# Speech To Text:
stt_pocketsphinx:
  acoustic_model: /opt/cefetmg/data/pocketsphinx/pt-br
  language_model: /opt/cefetmg/data/examples.lm
  dictionary: /opt/cefetmg/data/mixed.dict
  timeout_sec: 30.0
  vad_mode: 0
  audio_device: 1
  buffer_size: 2048
  sample_rate: 44100

stt_speech_recognition:

stt_snowboy:
  intent_texts:
    - 'ligar luz sala'
    - 'desligar luz sala'
    - 'ascender luz sala'
    - 'ligar luz quarto'
    - 'desligar luz quarto'
    - 'ascender luz quarto'
    - 'ligar luz cozinha'
    - 'desligar luz cozinha'
    - 'ascender luz cozinha'
    - 'abra porta sala'
    - 'luz sala ligada'
    - 'luz quarto ligada'
    - 'luz cozinha ligada'
    - 'porta sala aberta'
    - 'aumente volume'
    - 'diminua volume'
  keywords:
    - 'ligar'
    - 'desligar'
    - 'luz'
    - 'acender'
    - 'cozinha'
    - 'sala'
    - 'quarto'
    - 'abra'
    - 'porta'
    - 'ligada'
    - 'aberta'
    - 'fechada'
    - 'diminua'
    - 'aumente'
    - 'volume'
  models:
    - /opt/cefetmg/data/snowboy/ligar.pmdl
    - /opt/cefetmg/data/snowboy/desligar.pmdl
    - /opt/cefetmg/data/snowboy/luz.pmdl
    - /opt/cefetmg/data/snowboy/acender.pmdl
    - /opt/cefetmg/data/snowboy/cozinha.pmdl
    - /opt/cefetmg/data/snowboy/sala.pmdl
    - /opt/cefetmg/data/snowboy/quarto.pmdl
    - /opt/cefetmg/data/snowboy/abra.pmdl
    - /opt/cefetmg/data/snowboy/porta.pmdl
    - /opt/cefetmg/data/snowboy/ligada.pmdl
    - /opt/cefetmg/data/snowboy/aberta.pmdl
    - /opt/cefetmg/data/snowboy/fechada.pmdl
    - /opt/cefetmg/data/snowboy/diminua.pmdl
    - /opt/cefetmg/data/snowboy/aumente.pmdl
    - /opt/cefetmg/data/snowboy/volume.pmdl
  sensitivity: 0.5
  audio_gain: 0.7

intent_table:
  prhase_list:
    - 'ligar luz sala'
    - 'desligar luz sala'
    - 'ascender luz sala'
    - 'ligar luz quarto'
    - 'desligar luz quarto'
    - 'ascender luz quarto'
    - 'ligar luz cozinha'
    - 'desligar luz cozinha'
    - 'ascender luz cozinha'
    - 'abra porta sala'
    - 'luz sala ligada'
    - 'luz quarto ligada'
    - 'luz cozinha ligada'
    - 'porta sala aberta'
    - 'aumente volume'
    - 'diminua volume'
  payload_list:
    - "ON"
    - "OFF"
    - "ON"
    - "ON"
    - "OFF"
    - "ON"
    - "ON"
    - "OFF"
    - "ON"
    - "ON"
    - "STATUS"
    - "STATUS"
    - "STATUS"
    - "STATUS"
    - "increase"
    - "decrease"
  topic_list:
    - hass/switch/sala/luz1/set
    - hass/switch/sala/luz1/set
    - hass/switch/sala/luz1/set
    - hass/switch/quarto/luz1/set
    - hass/switch/quarto/luz1/set
    - hass/switch/quarto/luz1/set
    - hass/switch/cozinha/luz1/set
    - hass/switch/cozinha/luz1/set
    - hass/switch/cozinha/luz1/set
    - hass/switch/sala/porta1/set
    - hass/switch/sala/luz1/set
    - hass/switch/quarto/luz1/set
    - hass/switch/cozinha/luz1/set
    - hass/switch/sala/porta1/set
    - hass/speaker/volume
    - hass/speaker/volume

sensor: !include sensors.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
