homeassistant:
  # Name of the location where Home Assistant is running
  name: Genio
  # Location required to calculate the time the sun rises and sets
  latitude: -19.939623
  longitude: -43.998239
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 830
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Sao_Paulo
  # Customization file
  customize: !include customize.yaml
# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://127.0.0.1:3218

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Text to speech
tts:
  - platform: google
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300
    language: 'pt-br'


stt_pocketsphinx:
  acoustic_model: /home/homeassistant/.homeassistant/data/pocketsphinx/pt-br
  language_model: /home/homeassistant/.homeassistant/data/examples.lm
  dictionary: /home/homeassistant/.homeassistant/data/mixed.dict
  timeout_sec: 30.0
  vad_mode: 0
  audio_device: 1
  buffer_size: 2048
  sample_rate: 44100


media_player:
  - platform: vlc
    name: speaker_1
    arguments: '--alsa-audio-device=hw:0,0'

espeak_tts_success:

speech:

# Cloud
cloud:


intent_script:
  HassTurnOff:
    action:
      - service: wav_aplay.play_wav
        data:
          filename: /home/homeassistant/.homeassistantetc/wav/intent_recognized.wav
      - service: switch.turn_off
        entity_id: switch.living_room_lamp
  HassTurnOn:
    action:
      - service: wav_aplay.play_wav
        data:
          filename: /home/homeassistant/homeassistant/etc/wav/intent_recognized.wav
      - service: switch.turn_on
        entity_id: switch.living_room_lamp


mqtt: 
  broker: localhost   #if broker installed on the same computer than Home-Assistant 
  client_id: home-assistant 
  keepalive: 60
  port: 1883          #by default 
  protocol: 3.1       #by default
  #username: USERNAME #optional
  #password: PASSWORD #optional


switch:
  platform: mqtt
  name: "MeuLED"
  state_topic: "luz/status"
  command_topic: "luz/set"
  payload_on: "ON"   # A mensagem a ser enviada como payload para ligar;
  payload_off: "OFF" # A mensagem a ser enviada como payload para desligar;
  payload_available: "ONLINE"   
  payload_not_available: "OFFLINE" 
  optimistic: true   # Setado para true para manter o estado.
  qos: 0
  retain: true
  value_template: '{{ value.x }}'


input_boolean:
  successful_command:
    name: 'Command Success'
    initial: off
    icon: mdi:playlist-check

hotword_snowboy:
  model: /home/homeassistant/.homeassistant/data/snowboy/genio.pmdl
  name: hotword_genio

sensor: !include sensors.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
