
# Predição de Temperatura
#- platform: yr

# Teste
#- platform: random

# Time / Date
#- platform: time_date
#  display_options:
#      - 'time'
#      - 'date'
#- platform: worldclock
#  time_zone: America/Sao_Paulo
#  name: 'Brasília'

# Tópicos MQTT para ligar/desligar uma luz:
- platform: mqtt
  name: "luz"
  state_topic: "luz/status"
  availability_topic: "luz/available"
  state_value_template: "{{ value.x }}"
  state_format: 'json:value.x'
  qos: 0
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false